version: 2
services:
  demo-app:
    git_url: <https://github.com/cloud66/maestro-demo>
    git_branch: master
    ports:
    - container: 5000
      http: 80
      tcp: 22
    dockerfile_path: Dockerfile
databases:
- redis
